=== TrellixVulnTeam/ubuntu_git_test_ACLC/usr/share/libusermetrics/themes/color-theme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="themes" type="ThemeList"></xs:element>

	<xs:complexType name="ThemeList">
		<xs:sequence maxOccurs="unbounded" minOccurs="1">
			<xs:element name="theme" type="Theme"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Theme">
		<xs:sequence>
			<xs:element name="foreground" type="ColorSet"></xs:element>
			<xs:element name="background" type="ColorSet"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ColorSet">
		<xs:attribute name="start" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="main" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="end" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>
</xs:schema>

=== TrellixVulnTeam/ubuntu_git_test_ACLC/usr/share/libusermetrics/themes/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<themes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="color-theme.xsd">
	<theme>
		<foreground start="#e54c19" main="#ff9900" end="#e54c19" />
		<background start="#ff9900" main="#e54c19" end="#cc0000" />
	</theme>
	<theme>
		<foreground start="#cc19cc" main="#bf21bf" end="#7f334c" />
		<background start="#ff9900" main="#e54c19" end="#cc0000" />
	</theme>
	<theme>
		<foreground start="#cc19cc" main="#7f334c" end="#bf21bf" />
		<background start="#cc0000" main="#cc0000" end="#cc0000" />
	</theme>
	<theme>
		<foreground start="#cc19cc" main="#cc19cc" end="#cc19cc" />
		<background start="#cc19cc" main="#7f334c" end="#bf21bf" />
	</theme>
</themes>
